---
title: "Order book reconstruction from quotes and trades streams"
author: "Petr Fedorov"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    number_sections: TRUE
    figure_captions: TRUE
bibliography: coupling.bib    
---

# Introduction
## Continous-time double auction and LOB

Today, most liquid markets – including stocks, futures, and foreign exchange – are electronic, and adopt a continuous-time double auction mechanism using a limit order book (LOB), in which a transaction occurs whenever a buyer and a seller agree on a price[@bouchaud_trades_2018]. Cryptocurrenices are not exception. 

The mechanics of the countinous double auction or LOB trading may be briefly described as follows: 

1. Traders submit *limit orders* also called *quotes* and *market* or *market-limit* orders (i.e. quotes with the limit price better than the opposite quote best price already in LOB) 
<!-- 2. *Market* or *market-limit* orders are [matched](https://www.investopedia.com/terms/m/matchingorders.asp) with *quotes*  and executed to produce *trades*. -->
3. Unmatched *quotes* or unmatched amounts of *market-limit* orders reside in LOB's queues until matched with another *market* or *market-limit* order or cancelled by the participant who submitted it.

Market or market-limit orders are also often called the *aggressing* orders while the limit orders sitting in queues are called *resting* orders.

Note that not all matched orders are executed and produce trades. This happens due to self-match or self-trade prevention rules. See for example [CME Globex Self-Match Prevention](https://www.cmegroup.com/globex/trade-on-cme-globex/self-match-faq.html) or [Coinbase Markets Trading Rules 2.4 Self-trade prevention](https://www.coinbase.com/legal/trading_rules).

Thus in order to reconstruct the dynamics of the trading process and order book one needs  information about submitted quotes, market and market-limit orders and trades produced. As we will see below this information is not always provided by exchanges.


## Available data sets

Most of data sets containing information about quotes and trades consist of two separate loosely coupled files: a **trades** file recording  trades and an **quotes** file recording quote placements, changes and cancellations. Loosely coupled in this context means that records in **trades** file do not always have clearly identifiable corresponding records in **quotes** file as one would expect. By definition every trade shoud change some quote in LOB. So a matching or *coupling* procedure is required in order to establish the link between the **trades** and **quotes** files. This link is necessary to:

* Distinguish between quote changes due to limit order cancellation and market order execution
* Estimate size of submitted market orders
* Distinquish between limit order placements and market limit order placements

and, overall, to achieve the ultimate goal - to perform a complete order book reconstruction at every moment of time.

A recently published book [@abergel_limit_2016] uses the [Thomson Reuters Tick History (TRTH)](https://www.refinitiv.com/en/financial-data/market-data/tick-history) database tells us that

> Because one cannot distinguish market orders from cancellations just by observing changes in the limit order book (the “event” file), and since, the timestamps of the “trade” and “event” files are asynchronous, we use a matching procedure to reconstruct the order book events.

The reported matching rate of the above procedure is about 85% for CAC 40 stocks and as a byproduct the procedure outputs the sign of each matched trade, that is whether it is a buyer or a seller initiated trade. Note that TRTH data set does not even provide information about trade direction, it has to be deduced!

The description of similar issues we find in [@hautsch_modelling_2004]:

> A typical problem occurs when trades and quotes are recorded in separate trade and quote databases, like, for example, in the Trade and Quote (TAQ) database released by the NYSE. In this case, it is not directly identifiable whether a quote which has been posted some seconds before a transaction was already valid at the corresponding trade.

[Websocket API v2](https://www.bitstamp.net/websocket/v2/) of the cryptocurrency exchange Bitstamp gives access to the following information for every instrument traded:

 * **Live ticker** channel - information about trades. Unique ids of participating quote and market order are provided for each trade.
 * **Live orders** channel - information about quotes and market orders (all order creation, change and deletion events are reported).

As we will see later, events in these channels are not always sent in correct time order. It seems that some events are ommitted. Timestamps in Live tickers and Live orders channels are not synchronized: market order, changes of quotes and of market order itself caused by the execution of the market order, trades produced - all may have different timestamps. Substantial amount of matched orders are not executed due to [self-trade prevention](https://www.reddit.com/r/Bitstamp/comments/bbvut2/bitstamp_api_behaviour/?utm_source=share&utm_medium=web2x) policy of Bitstamp.
 

Similarly [Websocket API version 2.0] of the cryptocurrency exchange Bitfinex have the following channels (for every instrument traded):

 * **Trades** channel - information about trades. Ids of participating quote and market orders are not reported
 * **Raw book** channel - provides information about 100 best bid and 100 ask quotes. Market orders are not reported. Quotes reported as deleted when they fall beyond 100+ best quotes and created again with the same id when they return back. What was happening to them between these moments is not known. Since Bitfinex allows traders to change the price and volume of submitted quotes, the quotes may be changed or just cancelled. 
 
As well as at Bitstamp, records in Trades and Raw book channels are not synchronized.

It should be clear from the above that substantial effort is required to reconstruct the true dynamics of order submission, matching and execution.

# Reconstruction algorithm

## Order

Consider a definition given in [@bouchaud_trades_2018]:


> An order is a commitment, declared at a given submission time, to buy or sell a given volume of an asset at no worse than a given price. An order $x$ is thus described by four attributes:
>
> * its sign (or direction) $\epsilon = \pm 1$, ($\epsilon_x = +1$ for buy orders; $\epsilon_x = −1$ for sell orders),
  * its price $p_x$ ,
  * its volume $v_x > 0$, and
  * its submission time $t_x$.
>  
> We introduce the succinct notation $x := (\epsilon_x , p_x ,v_x, t_x )$.

[@bouchaud_trades_2018] then continues with a description of what they call The Trade-Matching Algorithm:

> Whenever a trader submits a buy (respectively, sell) order $x$, an LOB’s *trade-matching algorithm* checks whether it is possible for $x$ to match to existing sell (respectively,buy)orders $y$ such that $p_y \leq p_x$ (respectively, $p_y \geq p_x$). If so, the matching occurs immediately and the relevant traders perform a trade for the agreed amount at the agreed price. Any portion of $x$ that does not match instead becomes active at the price $p_x$, and it remains active until either it matches to an incoming sell (respectively, buy) order or it is cancelled. Cancellation usually occurs when the owner of an order no longer wishes to offer a trade at the stated price.

Above definition and description are incomplete:

* According to the definition, an order $x$ seems to be an immutable entity. But according to the Trade-Matching algorithm, a portion of $x$ may become 'active' and it is not clear how the quality of being 'active' is different from the mere existence of submitted orders,

* At what price the trade is performed - $p_x$ or $p_y$ - is not explicitly stated,

* It is not stated what will happen if $v_x \leq v_y$, etc. 

Surprisingly, the concept of order and operations of a continous double auction appear to be rather complicated things if one attempts to define them rigorously!

Hereafter is assumed that a single asset is traded and a single currency is used. 

```{definition Order, name="Order", label=order}
Suppose that:

a. $i \in \mathbb{Z}$ is called an *unique order identification*, 
a. $\mathcal{T^i}$ is a set of intervals $\mathcal{T^i} = \{T_k^i\}_{k=0}^{K^i}$ called *order intervals* where each $T_k^i$ is either a proper interval with endpoints $s_k^i \in \mathbb{R}_{>0}$, $e_k^i \in \mathbb{R}_{>0} \cup \{+\infty\}$, $s_k^i < e_k^i$  or a degenerate interval $\{s_k^i\}, s_k^i \in \mathbb{R}_{>0}$ and $\forall m \neq n : T_m^i \cap T_n^i = \emptyset$,

b. $\chi_{T_k^i} : \mathbb{R} \mapsto \{0,1\}$ is an indicator function of intervals in $\mathcal{T^i}$: 
$\chi_{T_k^i}(t) = \begin{cases} 1, & t \in T_k^i \\ 0, & \text{otherwise} \end{cases}$,

b. $\mathcal{P}^i = \{p_k^i\}_{k=0}^{K^i}$ is a set of constants $p_k^i \in \mathbb{R}_{>0}$ called *order prices*,

c. $\mathcal{V}^i = \{v_k^i\}_{k=0}^{K^i}$ is a set of constants called *order volumes*, such that either  $v_k^i \in \mathbb{R}_{<0}$ or $v_k^i \in \mathbb{R}_{>0}$,
  
d. Sets $\mathcal{P}^i$ and $\mathcal{V}^i$  satisfy the following condition $\forall k  \in [0, \ldots, N_i) : (p_k^i, v_k^i) \neq (p_{k+1}^i, v_{k+1}^i)$,

Then a vector-valued function $\mathbf{o}^i(t) : \mathbb{R}_{>0} \mapsto \mathbb{R}_{>0} \times \mathbb{R}$ representing a commitment to buy or sell a given volume $v$ of an asset at no worse than a given price $p$ at a particular time $t$  with a closed form:
$$
  \mathbf{o}^i(t) = (p^i(t), v^i(t)) = \Big( \sum_{k=1}^{K^i} p_k^i \chi_{T_k^i}(t),  \sum_{k=1}^{K^i} v_k^i \chi_{T_k^i}(t) \Big)
$$ is called an *order*. If $v_k^i \in \mathbb{R}_{<0}$ the order is a commitment to *sell* and is also called a *sell order*. If $v_k^i \in \mathbb{R}_{>0}$ the order is a commitment to *buy* and is also called a *buy order*.
```

Whenever it is clear from the context, we may also use the word order for:

 * An unique order identification $i$ number
 * An order as defined in [@bouchaud_trades_2018] (see above)
 * The value of tuple $(i, p^i(t_0), v^i(t_0))$ at the particular time $t_0$
 
Now we can define

```{definition Order Volume, name="Order Volume", label=order-volume}
The function $v^i(t)$ in definition \@ref(def:order) is called an *order volume*.
```


```{definition Order Price, name="Order Price", label=order-price}
The function $p^i(t)$ in definition \@ref(def:order) is called an *order price*.
```


```{definition Filled Volume and Trade, name="Filled Volume and Trade", label=fill-volume}
The filled volume $f^i(t)$ of an order $i$ at time $t$ is defined as: 
  $$
  f^i(t) = v^i(t) - \lim_{t^{'} \downarrow t} v^i(t^{'})
  $$
The tuple $(t, f^i(t), p^i(t))$ is called a *trade*. If order $i$ is a buy order then the trade is called a *sell trade*.  Otherwise it is a *buy trade*.
```

```{definition Cancelled Volume, name="Cancelled Volume", label=cancelled-volume}
The cancelled volume $c^i(t)$ of an order $i$ at time $t$ is defined as: 
  $$
  c^i(t) = \lim_{t^{'} \uparrow t} v^i(t^{'}) - v^i(t)
  $$
  
```




## Order Book

```{definition Order Book, name="Order Book", label=order-book}
A set of orders $\mathcal{O} = \{\mathbf{o}^i(t)\}_i$ is called an *order book*.
```


```{definition Order Placement Policy, name="Order Placement Policy", label=order-placement-policy}
Suppose that $\mathbb{O}$ is a set of all Order Books $\mathcal{O}$ as defined by \@ref(def:order-book). The function $$\mathcal{P}(\mathcal{O},i, t, p, v) : \mathbb{O} \times \mathbb{Z} \times  \mathbb{R}_{>0} \times \mathbb{R}_{>0} \times \mathbb{R}_{\neq 0} \mapsto \mathbb{O}$$ is called an *order placement policy*. It defines how order $i$ placement or update submitted at time $t$ with price $p$ and volume $v$ is added to the order book $\mathcal{O}$ and how the existing orders in $\mathcal{O}$ are modified, if necessesary. 
```


```{definition Best Bid Price, name="Best Bid Price", label=best-bid-price}
Suppose we are given an order book $\mathcal{O}$.  A (possibly empty) subset $\mathcal{B} =\{\mathbf{o}^b(t)\}_{v_k^b > 0} \subset \mathcal{O}$ of buy orders is called *bids* and the function $b(t)$ is defined as:
  $$
  b_{\mathcal{O}}(t) = \begin{cases} \max_{\mathbf{o}^b(t) \in \mathcal{B}} p^b(t), & \text{ if } \mathcal{B} \neq \emptyset \\0, & \text{ otherwise }  \end{cases}
  $$ is called *best bid price*.
```


```{definition Best Ask Price, name="Best Ask Price", label=best-ask-price}
Suppose we are given an order book $\mathcal{O}$. A (possibly empty) subset $\mathcal{A} =\{\mathbf{o}^a(t)\}_{v_k^a < 0} \subset \mathcal{O}$ of sell orders is called *asks* and the function $a(t)$ is defined as:
  $$
  a_{\mathcal{O}}(t) = \begin{cases} \min_{\mathbf{o}^a(t) \in \mathcal{A}} p^a(t) & \text{ if } \mathcal{A} \neq \emptyset \\ +\infty, & \text{ otherwise } \end{cases}
  $$ is called *best ask price*.
```

```{definition Matched Orders, name="Matched Orders", label=match}
Suppose we are given an order book $\mathcal{O}$. A buy order $\mathbf{o}^b(t) \in \mathcal{O}$ and a sell order $\mathbf{o}^s(t) \in \mathcal{O}$ are called *matched* if $\exists t : p^b(t) \geq p^s(t)$. If $$\lim_{t^{'} \uparrow t} p^s(t) \neq p^s(t)$$ then $\mathbf{o}^s(t)$ is called an *agressing* order and $\mathbf{o}^b(t)$ is called a *resting* order. Otherwise, $\mathbf{o}^b(t)$ is called an *agressing* order and $\mathbf{o}^s(t)$ is called a *resting* order.
The set of matched buy orders at time $t$ we will denote $\mathcal{M}_{\text{bid}}(t)$ and the set of matched sell orders - $\mathcal{M}_{\text{ask}}(t)$.
```



```{definition Ideal Order Book, name="Ideal Order Book", label=iob}
Suppose we are given an order book $\mathcal{O}$.  Then $\mathcal{O}$ is called *Ideal Order Book (IOB)* if the following conditions are satisfied: 
  
  a. Instantaneous Match Execution (IME)
$$ \lambda \Big( \{t : b_{\mathcal{O}}(t) \geq a_{\mathcal{O}}(t)\}\Big) = 0
(\#eq:instant-match)
  $$ where $\lambda(X)$ is the Lebesgue measure of set $X$.
  b. Volume Conservation (VC)
  $$
    \forall t \in \{t : b_{\mathcal{O}}(t) \geq a_{\mathcal{O}}(t)\} : \sum_{\mathbf{o}^b(t) \in \mathcal{M}_{\text{bid}}(t)} f^b(t) = \sum_{\mathbf{o}^s(t) \in \mathcal{M}_{\text{ask}}(t)} |f^s(t)|
    (\#eq:volume-conservation)
    $$

```



To make these definitions intuitevely clear, let's consider how IOB $\mathcal{O}$ would evolve under some  order placement policy $\mathcal{P}$ in a typical scenario of placing several buy and sell orders.  Note that our policy $\mathcal{P}$ given IOB retuns IOB. It is not the case in general and another order placement policy could retrun order book which is not IOB.

 1. A buy order is submitted at time $t_1$ with the price $p_1$ and volume $v_1$ and is transformed by $\mathcal{P}$ into $\mathbf{o}^1(t)$:
 
    + $\mathbf{o}^1(t)$ is added to $\mathcal{O}$: $$
\mathbf{o}^1(t) = \left[
 \begin{eqnarray}
  \mathcal{T}^1 & = & \{ [t_1, +\infty) \} \\
  \mathcal{P}^1 & = & \{ p_1 \} \\
  \mathcal{V}^1 & = & \{ v_1 \}
 \end{eqnarray} 
 \right.
 $$
 2. A sell order with price $p_2 < p_1$ and volume $|v_2| < |v_1|$ is submitted and transformed into $\mathbf{o}^2(t)$, matched with $\mathbf{o}^1(t)$ so the latter is partially filled at time $t_2$. All these actions are performed by $\mathcal{P}$. Note that the right endpoint $t_2$ below is included:
 
    + $\mathbf{o}^1(t)$ is changed: $$
    \mathbf{o}^1(t) = \left[
     \begin{eqnarray}
      \mathcal{T}^1 & = & \{ [t_1, t_2], (t_2, +\infty] \} \\
      \mathcal{P}^1 & = & \{ p_1, p_1 \} \\
      \mathcal{V}^1 & = & \{ v_1, v_1 - v_2 \}
    \end{eqnarray}
    \right.
  $$
    + $\mathbf{o}^2(t)$ is added to $\mathcal{O}$: $$
    \mathbf{o}^2(t) = \left[
     \begin{eqnarray}
      \mathcal{T}^2 & = & \{ {t_2} \} \\
      \mathcal{P}^2 & = & \{ p_2 \} \\
      \mathcal{V}^2 & = & \{ v_2 \}
    \end{eqnarray}
    \right.
  $$
 3. A sell order with price $p_3 < p_1$ and volume $v_3$ is submitted by the same trader as the one who submitted $\mathbf{o}^1(t)$. The order is transformed into $\mathbf{o}^3(t)$ and $\mathbf{o}^1(t)$ is cancelled (note that the right endpoint $t_3$ below is not included) due to self-trade prevention policy, which is part of $\mathcal{P}$, at time $t_3$ (as, for example, CME Globex would do by default):
    + $\mathbf{o}^1(t)$ is changed: $$
    \mathbf{o}^1(t) = \left[
     \begin{eqnarray}
      \mathcal{T}^1 & = & \{ [t_1, t_2], (t_2, t_3) \} \\
      \mathcal{P}^1 & = & \{ p_1, p_1 \} \\
      \mathcal{V}^1 & = & \{ v_1, v_1 - v_2 \}
    \end{eqnarray}
    \right.
  $$
    + $\mathbf{o}^2(t)$ remains the same,
    + $\mathbf{o}^3(t)$ is added to $\mathcal{O}$: $$
    \mathbf{o}^3(t) = \left[
     \begin{eqnarray}
      \mathcal{T}^3 & = & \{ [t_3, +\infty) \} \\
      \mathcal{P}^3 & = & \{ p_3 \} \\
      \mathcal{V}^3 & = & \{ v_3 \}
    \end{eqnarray}
    \right.
  $$


## Empirical Order and Order Book

Formally speaking, the reconstruction algorithm is supposed to produce Ideal Order Book from non-ideal data provided by an exchange.  The effort required varies by an exchange. For example [MOEX](https://www.moex.com/) provides data of close to ideal quality while [Bitfinex](https://www.moex.com/) does not report unique order identifications for trades and omits market orders altogether.



```{definition Quotes Stream, name="Quotes Stream", label=quotes-stream}
A set of tuples $$\mathcal{S}_Q = \bigcup_i \{(t_k^i, i, p_k^i, v_k^i)\}_{k=1}^{K^i} = \bigcup_i \mathcal{S}_Q^i$$ where

 a. $t_k^i$ is a timestamp of the order $i$ update.
 b. $i$ is an identification number of the order.
 c. $p_k^i \geq 0$ is an order price at $t_k^i$. If $p_k^i = 0$ then the order $i$ is deleted at $t_k^i$ (executed or cancelled).
 d. $v_k^i \neq 0$ is a order volume at $t_k^i$. If $v_k^i < 0$ then it is a sell order. Otherwise it is a buy order.
 
is called *Quotes Stream*. The set $\mathcal{S}_Q^i = \{(t_k^i, i, p_k^i, v_k^i)\}_{k=1}^{K^i}$ is called an *order $i$ stream*.
```

```{definition Trades Stream, name="Trades Stream", label=trades-stream}
A set of tuples $\mathcal{S}_T = \{(t_r, b_r, s_r, p_r, v_r)\}_{r=0}^{R}$ where

 a. $t_r$ is a timestamp of the trade
 b. $b_r$ is a buy order identification number 
 b. $s_r$ is a sell order identification number 
 b. $m \neq n \implies \ (b_m, s_m) \neq (b_n, s_n)$
 b. $p_r > 0$ is a trade price
 b. $v_r \neq 0$ is a trade volume. If $v_r > 0$ then it is a buy trade. Otherwise it is a sell trade
 
is called *Trades Stream*.
```




```{definition Empirical Order, name="Empirical Order", label=empirical-order}
An order $\hat{\mathbf{o}}^{i}(t)$ as defined by \@ref(def:order) which has been in some way constructed from the *order stream* $\{(t_k^i, i, p_k^i, v_k^i)\}_{k=1}^{K^i} \in \mathcal{S}_Q$ as defined by \@ref(def:quotes-stream) is called an *empirical order*.
```


```{definition Empirical Order Book, name="Empirical Order Book", label=eob}
A set of empirical orders $\hat{\mathcal{O}} = \{\hat{\mathbf{o}}^i(t)\}_i$ is called *Empirical Order Book(EOB)*.
```




A typical exchange gives us some kind of event stream and, separately, some kind of trade stream with various level of details. 


## Initial Reconstruction

To reconstruct an empirical order $\hat{\mathbf{o}}^{i}(t)$ as defined by \@ref(def:empirical-order) from the *order stream* $\mathcal{S}_Q^i = \{(t_l^i, i, p_l^i, v_l^i)\}_{l=1}^{L^i}$ as defined by \@ref(def:quotes-stream) one needs to define the set of intervals $\mathcal{T^i}$ since order prices $\mathcal{P}^i$ and order volumes $\mathcal{V}^i$ are unambiguously defined by the order stream $\mathcal{S}_Q^i$.

It appears that timestamps $t_l^i$ of the order $i$ updates (\@ref(def:quotes-stream)) gives us some endpoints of order intervals as defined by the rules below.

 a. The first interval is $[t_1^i, t_2^i)$.
 a. If $l \geq 2 \land v_{l-1}^i \leq v_l^i$ then $l$'s interval is $[t_{l}^i, t_{l+1}^i)$ since either the price of order $i$ has been changed or its volume has been increased 
 a. If $l \geq 2 \land v_{l-1}^i > v_l^i$ then $l$'s interval is $(t_{l}^i, t_{l+1}^i)$ for it is not possible to say based solely on the Quotes Stream data whether order $i$ volume has been decreased due cancellation or fill at time $t_l^i$.
 
Note that $\hat{\mathbf{o}}^{i}(t)$ has not been defined yet at points $t_{l}^i : v_{l-1}^i > v_l^i$ so the data provided by Trades Stream need to be used, i.e. a coupling of quotes and trades streams need to be performed.
 
 
## Quotes and Trades Coupling 

TBD


## Enforcement of IME condition in EOB

TBD

## Enforcement of VC condition in EOB

TBD

# Results

TBD

## Application to Bitstamp data

TBD

## Application to Bitfinex data

TBD

# Discussion

TBD

```{r}
sum(36*1/1:36)
```



# References





