# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalculateTradingPeriod <- function(depth_changes, volume, debug_level) {
    .Call(`_obadiah_CalculateTradingPeriod`, depth_changes, volume, debug_level)
}

CalculateOrderBookSnapshots <- function(depth_changes, tick_size, ticks, type, debug_level) {
    .Call(`_obadiah_CalculateOrderBookSnapshots`, depth_changes, tick_size, ticks, type, debug_level)
}

CalculateOrderBookChanges <- function(depth_changes, debug_level) {
    .Call(`_obadiah_CalculateOrderBookChanges`, depth_changes, debug_level)
}

ChangeTickSize <- function(depth_changes, tick_size, debug_level) {
    .Call(`_obadiah_ChangeTickSize`, depth_changes, tick_size, debug_level)
}

DiscoverPositions <- function(computed_trading_period, phi, rho, debug_level) {
    .Call(`_obadiah_DiscoverPositions`, computed_trading_period, phi, rho, debug_level)
}

DiscoverDrawUpDowns <- function(precomputed_prices, epsilon, debug_level) {
    .Call(`_obadiah_DiscoverDrawUpDowns`, precomputed_prices, epsilon, debug_level)
}

spread_from_depth <- function(timestamp, price, volume, side) {
    .Call(`_obadiah_spread_from_depth`, timestamp, price, volume, side)
}

