# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DrawsFromSpread <- function(timestamp, price, draw_type, params) {
    .Call(`_obadiah_DrawsFromSpread`, timestamp, price, draw_type, params)
}

spread_from_depth <- function(timestamp, price, volume, side) {
    .Call(`_obadiah_spread_from_depth`, timestamp, price, volume, side)
}

draws_from_spread <- function(timestamp, price, gamma_0, theta) {
    .Call(`_obadiah_draws_from_spread`, timestamp, price, gamma_0, theta)
}

